config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'events/index'
  get 'events/create'
  root to: 'events#index'
  resources :events, only: %i[index create edit update]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :title, :start_on, :end_on, presence: true
  validate :end_before_start

  scope :for_week, lambda { |start_of_week|
    where(
      'start_on >= :start_of_week AND start_on <= :end_of_week ',
      start_of_week: start_of_week,
      end_of_week: start_of_week + 6.days
    ).order(start_on: :asc)
  }

  private

  def end_before_start
    return false if end_on.blank? || start_on.blank?
    return true if (end_on > start_on) || (end_on == start_on)
    errors.add(:end_on, I18n.t('errors.messages.end_before_start'))
    false
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[edit update]
  def index
    empty_event!
  end

  def edit; end

  def update
    @event.update(event_params)
  end

  def create
    @event = Event.new(event_params)
    return empty_event! if @event.save
    render 'fail_form'
  end

  private

  def empty_event!
    @event = Event.new
  end

  def event_params
    params.require(:event).permit(:title, :description, :start_on, :end_on)
  end

  def events
    @events ||= Events.new(Event.for_week(start_of_week))
  end

  #--- Helpers ---

  helper_method def events_on(date)
    events.on(date)
  end

  helper_method def start_of_week
    return @start_of_week if @start_of_week.present?
    start = params.fetch(:start_of_week, nil)
    @start_of_week = start.present? ? Date.parse(start) : Date.current.beginning_of_week
    @start_of_week
  end

  helper_method def previous_start_of_week
    start_of_week - 7.days
  end

  helper_method def next_start_of_week
    start_of_week + 7.days
  end

  helper_method def end_of_week
    start_of_week + 6.days
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/events/calendar/_add_modal.html.slim
.modal role="dialog" tabindex="-1" id="addModal"
  .modal-dialog role="document" id="addModalContent"
    = render 'events/calendar/form', event: @event

app/views/events/calendar/_arrows.html.slim
.row
  .col
    = link_to events_path(start_of_week: previous_start_of_week), remote: true, class: 'badge badge-info' do
      | &lsaquo;
  .col.text-right
    = link_to events_path(start_of_week: next_start_of_week), remote: true, class: 'badge badge-info' do
      | &rsaquo;

app/views/events/calendar/_component.html.slim
= render 'events/calendar/add_modal'

.calendar
  .calendar__switch
    = render 'events/calendar/arrows'
  .calendar__days
    = render 'events/calendar/days'

app/views/events/calendar/_days.html.slim
- (start_of_week..end_of_week).each do |day|
  .calendar__days-day data-toggle="tooltip" title="Double click to add Event" data-day="#{day}"
    .calendar__days-day-wday= Date::DAYNAMES[day.wday]
    .calendar__days-day-date= l day
    .calendar__days-day-events
      - events_on(day).each do |event|
        .calendar__days-day-events-item style="background-color: ##{"#{event.id}#{event.title}".hash.to_s(16).slice(1,6)}"
          = event.title
          .text-right
            = link_to 'Edit', edit_event_path(event), remote: true, class: 'btn btn-primary'

app/views/events/calendar/_form.html.slim
= form_for event, url: event.persisted? ? event_path(event) : events_path, id: 'add_event_form', remote: true do |f|
  = hidden_field_tag :start_of_week, start_of_week

  .modal-content
    .modal-header
      h5.modal-title Add new Event
      button.close aria-label="Close" data-dismiss="modal" type="button"
        span aria-hidden="true"  &times;
    .modal-body
      - if event.errors.any?
        .alert.alert-danger
          - event.errors.full_messages.each do |msg|
            p= msg
      .form-group
        label
          | Title
          span.input-required *
        = f.text_field :title, class: 'form-control', required: true
      .form-group.row
        .col
          label
            | Start
            span.input-required *
          = f.date_field :start_on, class: 'form-control', required: true
        .col
          label
            | End
            span.input-required *
          = f.date_field :end_on, class: 'form-control', required: true
      .form-group
        label Description
        = f.text_area :description, class: 'form-control'
    .modal-footer
      button.btn.btn-secondary.text-left data-dismiss="modal" type="button" Close
      button.btn.btn-success type="submit" Add

app/views/events/create.js.erb
$('#addModal').modal('toggle');
$('#calendar').html('<%= j render 'events/calendar/component' %>');
$('#add_event_form').find('input[type=text], textarea').val('');

app/views/events/edit.js.erb
$('#calendar').html('<%= j render 'events/calendar/component' %>');
$('#addModal').modal('toggle');

app/views/events/fail_form.js.erb
$('#addModalContent').html('<%= j render 'events/calendar/form', event: @event %>');

app/views/events/index.html.slim
.container-fluid
  h1 Calendar of Events

  #calendar
    = render 'events/calendar/component'

app/views/events/index.js.erb
$('#calendar').html('<%= j render 'events/calendar/component' %>');

app/views/events/update.js.erb
$('#addModal').modal('hide');
$('#calendar').html('<%= j render 'events/calendar/component' %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendul</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>